version 0.2

phases: 
  install: 
    commands: 
      - echo installing dependencies 
      - npm ci

  build: 
    commands: 
      - echo running build 
      - npm run build 

  post_build: 
    commmands: 
      - echo build completed successfully 

artifacts: 
  files: 
    - '**/*'
  base-directory: dist
  discard-paths: no


