version 0.2

phases: 
  install: 
    commands: 
      - echo installing dependencies 
      - npm ci

  build: 
    commands: 
      - echo running build 
      - node app.js 

  post_build: 
    commmands: 
      - echo build completed successfully 

artifacts: 
  files: 
    - '**/*'


